server:
  port: 81
  contextPath: /PQR
  
spring:
  datasource:
    url: jdbc:mysql://localhost/pqr
    username: root
    password: 
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf.cache: false
  
security:
  basic:
    enabled: false

logging:
 level:
  org:
    springframework:
      security: DEBUG